### ISSUE TITLE
Failed to resolve

### ISSUE THREAD

**Issue by martarodriguezm** [gtcompscientist/KwikPicker#3]
I tried all the versions but it has been imposible to resolve de dependency with Gradle:

Failed to resolve: co.csadev.kwikpicker:2.0.0

Failed to resolve: co.csadev.kwikpicker:1.0.0

Failed to resolve: co.csadev.kwikpicker:1.0.1

**Comment by gtcompscientist** [comment]
Are you referencing `jcenter()` in your dependencies?

**Comment by martarodriguezm** [comment]
Yes, I do.

**Comment by gtcompscientist** [comment]
Ah! I think you are missing the colon in the after `co.csadev`: 
`implementation 'co.csadev:kwikpicker:2.0.0'`

**Comment by martarodriguezm** [comment]
You are right, with the colon it works.
You should change the readme file, because you have there the mistake:

<img width="570" alt="screen shot 2018-07-18 at 07 19 26" src="https://user-images.githubusercontent.com/1157385/42861358-f14b39ce-8a5a-11e8-9e48-257371dc1563.png">

Thank you very much!
